import type { CountryOption } from "@/components/stacked/types";

export const catalog: CountryOption[] = [
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    featured: true,
    spotlight: "Best for coast-to-coast travel",
    plans: [
      {
        id: "us-unlimited",
        name: "Unlimited Explorer",
        dataLabel: "Unlimited data",
        periodDays: 30,
        priceCents: 4800,
        currency: "USD",
        description: "Unlimited high-speed data with hotspot support and throttling after 60GB.",
        badge: "Most popular",
      },
      {
        id: "us-weekend",
        name: "Weekend Getaway",
        dataLabel: "8 GB",
        periodDays: 7,
        priceCents: 2200,
        currency: "USD",
        description: "Perfect for quick trips with generous tethering included.",
      },
      {
        id: "us-business",
        name: "Business Flex",
        dataLabel: "25 GB",
        periodDays: 30,
        priceCents: 3600,
        currency: "USD",
        description: "Priority access on partner 5G networks with Wi-Fi calling enabled.",
      },
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    featured: true,
    spotlight: "Roam all of England, Scotland & Wales",
    plans: [
      {
        id: "uk-unlimited",
        name: "Unlimited Britain",
        dataLabel: "Unlimited data",
        periodDays: 15,
        priceCents: 3600,
        currency: "USD",
        description: "Uncapped data with EU roaming add-on included.",
      },
      {
        id: "uk-weekend",
        name: "City Break",
        dataLabel: "6 GB",
        periodDays: 10,
        priceCents: 1900,
        currency: "USD",
        description: "Sized for theatre weekends and countryside escapes.",
      },
    ],
  },
  {
    code: "JP",
    name: "Japan",
    flag: "🇯🇵",
    featured: true,
    spotlight: "Optimised for Shinkansen routes",
    plans: [
      {
        id: "jp-unlimited",
        name: "Unlimited Kansai",
        dataLabel: "Unlimited data",
        periodDays: 15,
        priceCents: 4200,
        currency: "USD",
        description: "Unlimited 5G with bilingual support and hotspot.",
        badge: "Premium",
      },
      {
        id: "jp-adventure",
        name: "Explorer",
        dataLabel: "12 GB",
        periodDays: 21,
        priceCents: 3500,
        currency: "USD",
        description: "Balanced for longer trips with coverage from Hokkaido to Okinawa.",
      },
    ],
  },
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    plans: [
      {
        id: "es-unlimited",
        name: "Unlimited Siesta",
        dataLabel: "Unlimited data",
        periodDays: 15,
        priceCents: 3100,
        currency: "USD",
        description: "Unlimited data with hotspot for the Iberian peninsula.",
      },
      {
        id: "es-weekend",
        name: "Barcelona Weekender",
        dataLabel: "5 GB",
        periodDays: 7,
        priceCents: 1700,
        currency: "USD",
        description: "Great for short tapas-fuelled adventures.",
      },
    ],
  },
  {
    code: "TH",
    name: "Thailand",
    flag: "🇹🇭",
    plans: [
      {
        id: "th-unlimited",
        name: "Unlimited Islands",
        dataLabel: "Unlimited data",
        periodDays: 12,
        priceCents: 2800,
        currency: "USD",
        description: "Unlimited coverage from Bangkok to Koh Samui.",
      },
      {
        id: "th-adventure",
        name: "Adventure",
        dataLabel: "10 GB",
        periodDays: 20,
        priceCents: 2600,
        currency: "USD",
        description: "Extended trips with multi-city roaming included.",
      },
    ],
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    plans: [
      {
        id: "au-unlimited",
        name: "Unlimited Outback",
        dataLabel: "Unlimited data",
        periodDays: 30,
        priceCents: 5200,
        currency: "USD",
        description: "Unlimited data with Telstra and Optus 5G access.",
      },
      {
        id: "au-weekend",
        name: "Surf Weekender",
        dataLabel: "7 GB",
        periodDays: 10,
        priceCents: 2400,
        currency: "USD",
        description: "Sized for beach trips and city sightseeing.",
      },
    ],
  },
];

export function findCountryByCode(code: string) {
  return catalog.find((country) => country.code === code);
}
